### ISSUE TITLE
JSON::Tiny is missing from dependences

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#1]
Or maybe it should be eliminated and superseded by JSON::Fast.

**Comment by noisegul** [comment]
`JSON::Fast` is already the only one being used, and it's a drop-in replacement.
Nothing makes use of `JSON::Tiny`, or am I missing something?

See:
https://github.com/noisegul/perl6-p6doc/blob/34d17d1917ea25d091f0bf660d1cae7c384fb3fc/lib/P6doc.pm6#L220

**Comment by JJ** [comment]
Yes, you are. Do a git grep JSON or simply go to doc/Language/operators.pod6
