### ISSUE TITLE
Optional pager usage

### ISSUE THREAD

**Issue by noisegul** [noisegul/perl6-p6doc#15]
In the old `p6doc`, using a pager for the output was the default, with the ability to deactivate it. I believe the opposite approach is better:

Print output to stdout by default and add the optional ability to show it through a pager, should that still be desired.

Reasoning: It's more in line with how most command-line utilities work.

**Comment by noisegul** [comment]
An argument against that could be that the Perl6 documentation is not entirely suited for raw command line consumption. If it turns out that paging is the far more popular choice it could make sense to have it as the default behavior.

**Comment by JJ** [comment]
As a matter of fact, git uses a pager by default, and if I remember
correctly, man passes stuff through less or more. I think that people
expect paging to be set by default, and in absence of anyone requesting a
change in behavior, I would leave it the way it is now.

**Comment by noisegul** [comment]
Hmm that is true.
For a different example, the `go doc` command does directly print to stdout without paging.

I currently believe that keeping/reinstating paging as the default probably makes most sense here.

**Comment by JJ** [comment]
Maybe you could also add a no-pager option on the side. That's probably done, though.

**Comment by noisegul** [comment]
Added, will include it as the `-n` option.
