### ISSUE TITLE
A different name for p6doc

### ISSUE THREAD

**Issue by noisegul** [noisegul/perl6-p6doc#22]
**Description:**
Naming appears to be a bit intertwined, on Rakudo Star 2019.03  [github.com/perl6/doc](https://github.com/perl6/doc) is listed with the Identity `p6doc:ver<1.002001>` and under the name `Perl6::Documentable`.

`zef info Perl6::Documentable`

```
- Info for: Perl6::Documentable
- Identity: p6doc:ver<1.002001>
- Recommended By: /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site
- Installed: Yes
Description:	 Perl 6 documentation (tools and docs)
License:	 Artistic-2.0
Source-url:	 git://github.com/perl6/doc.git
Provides: 10 modules
Support:
#   source:	git://github.com/perl6/doc.git
Depends: 9 items
```

Looking at [github.com/perl6/doc's META6.json](https://github.com/perl6/doc/blob/633932784baa39773ec533076bc50df1d30f12e3/META6.json#L2) it uses the name
`p6doc` for the whole repository, not just the `p6doc` command.

To simply avoid any problems and name clashes related to this whole situation in the future it
might be beneficial to rename the `p6doc` command line tool  project in this repository.

Let me know what you think.

**Relevant issues:**
- https://github.com/perl6/doc/issues/2896 (possibly)

**Comment by JJ** [comment]
Hi,

El lun., 22 jul. 2019 a las 18:53, Joel (<notifications@github.com>)
escribió:

> *Description:*
> Naming appears to be a bit intertwined, on Rakudo Star 2019.03
> github.com/perl6/doc is listed with the Identity p6doc:ver<1.002001> and
> under the name Perl6::Documentable.
>

That's correct. We haven't yet split it off the perl6/doc site. I'm working
with @antoniogamiz to do it.

Looking at github.com/perl6/doc's META6.json
> <https://github.com/perl6/doc/blob/633932784baa39773ec533076bc50df1d30f12e3/META6.json#L2>
> it uses the name
>
> p6doc for the whole repository, not just the p6doc command.
>
> To simply avoid any problems and name clashes related to this whole
> situation in the future it
> might be beneficial to rename the p6doc command line tool project in this
> repository.
>
Not really. We will simply split the repository in two, leaving the
documentation proper in one place and the tooling in others.

**Comment by noisegul** [comment]
Alright, thanks for clarifying. In that case I'll close this issue.
