### ISSUE TITLE
Multiclass files support

### ISSUE THREAD

**Issue by antoniogamiz** [noisegul/perl6-p6doc#32]
This issue is related to https://github.com/antoniogamiz/Perl6-Documentable/issues/66. I am going to add multi-class file support to `Documentable`, but I saw this comment in your code:

https://github.com/noisegul/perl6-p6doc/blob/74b723a7e05efaf177af2a72401e4d84c6969ab8/lib/P6doc.pm6#L220

And I thought `p6doc` should support this too.

In case you do not know it, `load` returns an array with all pods (that means, all `=begin pod =end pod` blocks found. So if you load the example in the previous issue, you will see that `Pod::Load` will returns an array containing two elements.

**Comment by noisegul** [comment]
I'm aware, but let's have a look at this, because it leaves questions that are not answered by the linked discussions.
Which parts/files of the standard documentation will be squashed to make use of multiclass in the immediate future? 

> And I thought p6doc should support this too.

For searching routines at least this is not relevant, if `Perl6::Documentable::Registry` supports it, `p6doc` does so as well. For Types this becomes a topic.

**Comment by antoniogamiz** [comment]
Exception classes will use multi-class file support.

**Comment by Tyil** [comment]
This sounds like it may make @noisegul work much harder for very little gain. Is there a reason why exception classes have to be exceptional in this regard?

**Comment by antoniogamiz** [comment]
I implemented this because of https://github.com/perl6/doc/issues/516 and https://github.com/perl6/doc/issues/517.

**Comment by noisegul** [comment]
If that is the decided direction things will go it will be helpful to outline and clearly define which parts of the documentation will harbor multiple pods in single files.

I will comment in the relevant discussion on it.

**Comment by antoniogamiz** [comment]
As I said earlier, this feature will be used for exception classes due to the huge amount of those and its length.

**Comment by noisegul** [comment]
I know you said that, it does not affect my statement, which was more general in nature.
So to clarify: This will be used for exception classes, but you don't have plans to apply this treatment to other classes?

**Comment by antoniogamiz** [comment]
Probably not. Because the others classes are quite longer than exceptions and more "specific".

**Comment by noisegul** [comment]
Alright, thank you for clarifying.
