### ISSUE TITLE
Remaining steps to make this module installable

### ISSUE THREAD

**Issue by noisegul** [noisegul/perl6-p6doc#36]
During development this has not been much of a concern, but it is now time to investigate
which steps remain to make this module installable, or what could possibly prevent that and
document them for future users or contributors.

An example for this would be that there are naturally problems with Rakudo Star, because of the way modules are named and included:

The whole [perl6/doc](https://github.com/perl6/doc) holds the identity `p6doc`, in Rakudo Star it still ships with `Perl6::TypeGraph`, of which a newer version has already been split out.
This newer version is required by `Perl6::Documentable` and through that, by `p6doc` as well.

**Comment by JJ** [comment]
You should probably open an issue in the doc repo so that we can make the transition.
