### ISSUE TITLE
bin is probably not a good place for `index.data`

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#4]
Because it's likely that it's write-protected. Unless it's going to be generated when installed and that's it (which does not seem to be the case), you need to take care or permissions.

**Comment by noisegul** [comment]
I agree.
The location of `index.data` is indeed quite a problem, on a regular (not this repo) `p6doc` install it's also in a bad location. Even if one leaves out the potential problems coming from folder permissions, it's really not acceptable to pollute userspace, such as `/usr/local/bin/` (rakudo install on OSX).

**Comment by noisegul** [comment]
One better alternative, and my proposal as a starting point, would be `~/.perl6`, as at least rakudo-star users have that, and there it won't pollute other places.
However it shouldn't be the only possible location.
