### ISSUE TITLE
Add use-ok tests

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#5]
Basic compilation tests.

**Comment by noisegul** [comment]
I added tests for module loading:

https://github.com/noisegul/perl6-p6doc/blob/34d17d1917ea25d091f0bf660d1cae7c384fb3fc/t/00-load.t#L8-L13

**Comment by JJ** [comment]
Please try and always close issues from a commit (as well as refer to it in every commit that works towards that issue)
