### ISSUE TITLE
Script should be reduced to the bare minimum

### ISSUE THREAD

**Issue by JJ** [noisegul/perl6-p6doc#6]
The more you offload to library, the more it's precompiled and faster to load (and test)
Ideally, all MAIN should simply call a function in a library (which could be tested instead of testing directly the executable)

**Comment by noisegul** [comment]
All the script code does now reside inside its own submodule, see 12a816a

**Comment by JJ** [comment]
Again, you can directly refer to issues from a commit by simply inserting their commit number.

**Comment by JJ** [comment]
Also, the main point of this issue is to be able to test every single MAIN invocation. so you need to add tests for them.
